package com.kappadrive.dao.api;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks that DAO method should be generated by select pattern.
 */
@Retention(RetentionPolicy.SOURCE)
@Target(ElementType.METHOD)
public @interface Select {

    /**
     * Setup select iterator type.
     * By default it is <code>AUTO</code>, which means next:
     * - <code>ALL</code> will be used for select without query args
     * (Offset and Limit are still available)
     * - <code>EQ</code> will be used for select with at least one query arg
     *
     * @return iterator for selector.
     */
    Iterator value() default Iterator.AUTO;

    /**
     * Specifies index for select query.
     */
    @Retention(RetentionPolicy.SOURCE)
    @Target(ElementType.METHOD)
    @interface Index {

        /**
         * Returns index for select query.
         *
         * @return index for select query.
         */
        String value();
    }

    /**
     * Marks select method parameter to be used as <code>offset</code>.
     * This parameter should have primitive type <code>int</code>.
     */
    @Retention(RetentionPolicy.SOURCE)
    @Target(ElementType.PARAMETER)
    @interface Offset {
    }

    /**
     * Marks select method parameter to be used as <code>limit</code>.
     * This parameter should have primitive type <code>int</code>.
     */
    @Retention(RetentionPolicy.SOURCE)
    @Target(ElementType.PARAMETER)
    @interface Limit {
    }

    /**
     * Iterator for select query.
     */
    enum Iterator {
        AUTO,
        EQ,
        REQ,
        ALL,
        LT,
        LE,
        GE,
        GT,
        BITS_ALL_SET,
        BITS_ANY_SET,
        BITS_ALL_NOT_SET,
        OVERLAPS,
        NEIGHBOR,
        ;
    }
}
